.\" Manpage for configure.
.\" Contact eric@arpa.ph to correct errors or typos.
.TH configure 1 "18 Jan 2021" "1.0" "configure man page"
.SH NAME
configure \- PAREF App Server Builder
.SH DESCRIPTION
PAREF App Server Builder is a script to automate the PAREF SMS server build process in the cloud. The script uses a configuration file located at /etc/parefconfigure/configure.conf which loads the parameters of the build process as environment variables.
.SH OPTIONS
./configure


.SH SEE ALSO
configure(1), configure.conf(2)
.SH BUGS
No known bugs.
.SH AUTHOR
Eric Fajardo (eric@arpa.ph)
