.\" Manpage for configure.
.\" Contact eric@arpa.ph to correct errors or typos.
.TH configure 1 "18 Jan 2021" "1.0" "configure man page"
.SH NAME
configure \- PAREF App Server Builder
.SH DESCRIPTION
PAREF App Server Builder is a script to automate the PAREF SMS server build process in the cloud. The script uses a configuration file located at /etc/parefconfigure/configure.conf which loads the parameters of the build process as environment variables.
.SH OPTIONS
The script can be run by pulling the stable released from the repository:

Command:

wget https://github.com/arpacorp/parefasb/releases/download/{VERSION_NO}/parefasb.zip && unzip parefasb.zip && cd parefasb && chmod +x configure && /usr/bin/bash configure

The configuaration option are as follows:

[MISC_SETTINGS].

EMAIL           - Defines the email address of the server administrator.

XIND            - Defines the default index file for the web server.

XINF            - Defines the default phpinfo for the server.

XHST            - Defines the /etc/hosts file.

XFST            - Defines the /etc/fstab entry.

BASEPATH        - Defines the base path /etc/parefconfigure.

APACHEDIR       - Defines the /etc/apache2 directory.

PHPDIR          - Defines the /etc/php/5.6/apache2 directory.

LOGFILE         - Defines the configure.log.

WEBROOT         - Defines the default DocumentRoot.

STORPUB         - Defines the /storage/public path.

STORCON         - Defines the /storage/config path.

TMPDIR          - Defines the /tmp file location.

[BASE_PACKAGES].

BASEPKGS_U      - Defines the Ubuntu packages separated by a pipe |.

DMODULE_U       - Defines the Apache modules to be disabled by default.

EMODULE_U       - Defines the Apache modules to be enabled.

BASEPKGS_C      - Defines the RHEL/CentOS packages separated by a pipe |.

[CUSTOM_CONFIG].

CUSTOM_ENV      - Defines the environment file env.txt.

CUSTOM_WELCOME  - Defines the welcome file for 000.txt.

CUSTOM_SERVERCODE       - Defines the server code file for 001.txt.

CUSTOM_SERVERNAME       - Defines the question file for 002.txt.

CUSTOM_HTTPSPORT        - Defines the question file for 003.txt.

CUSTOM_SERVERTOKENS     - Defines the question file for 004.txt.

CUSTOM_SERVERSIGNATURE  - Defines the question file for 005.txt.

CUSTOM_CERTBOT          - Defines the question file for 006.txt.

CUSTOM_SECURITY         - Defines the question file for 007.txt.

CUSTOM_DISABLEHTTP      - Defines the question file for 008.txt.

CUSTOM_MAXUPLOADSIZE    - Defines the question file for 009.txt.

CUSTOM_CONFIRM          - Defines the question file for 010.txt.

.SH SEE ALSO
configure(1), configure.conf(2)
.SH BUGS
No known bugs. Hit us up at #supportchannel for issues.
.SH AUTHOR
Eric Fajardo (eric@arpa.ph)
